# Generated by Django 4.2.1 on 2023-05-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
