# Generated by Django 2.2 on 2022-01-11 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='context',
            new_name='content',
        ),
    ]
