# Generated by Django 4.1.3 on 2022-12-10 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admdatetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 15, 31, 54, 756391)),
            preserve_default=False,
        ),
    ]
