# We will going to need a lots of command like:
# python manage.py runserver
# python manage.py makemigrations
# python manage.py migrate
# and others
# so rather then write all of these command from the terminal we will going to create a makefile

# Creating the custom command
runserver: # Now we can run 'make runserver'
	poetry run python manage.py runserver
